apiVersion: v1
kind: Service
metadata:
    name: alfred-api-svc
    labels:
        app: alfred-api
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: alfred-api
