name: Continuos Deployment

on:
  push:
    branches:
      - main

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.release_created }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Prepare release
        id: release-please
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          token: ${{secrets.GITHUB_TOKEN}}
          release-type: simple
      - name: Check outputs
        env:
          RELEASE_CREATED: ${{ steps.release-please.outputs.release_created }}
          TAG_NAME: ${{ steps.release-please.outputs.tag_name }}
          MAJOR: ${{ steps.release-please.outputs.major }}
          MINOR: ${{ steps.release-please.outputs.minor }}
          PATCH: ${{ steps.release-please.outputs.patch }}
        run: |
          echo release_created: $RELEASE_CREATED
          echo tag_name: $TAG_NAME
          echo major: $MAJOR
          echo minor: $MINOR
          echo patch: $PATCH

  generate-release:
    runs-on: ubuntu-latest
    needs:
      - prepare-release
    outputs:
      image: ${{ steps.build-image.outputs.image }}
    steps:
      - name: Check Inputs
        env:
          RELEASE_CREATED: ${{ needs.prepare-release.outputs.release_created }}
        run: |
          echo release_created: ${{ needs.prepare-release.outputs.release_created }}
          echo RELEASE_CREATED: $RELEASE_CREATED
      - name: Checkout repository
        uses: actions/checkout@v3
        if: ${{ needs.prepare-release.outputs.release_created }}
      - name: Read version
        if: ${{ needs.prepare-release.outputs.release_created }}
        id: read-version
        run: |
          VERSION=$(cat version.txt)
          echo Version read: $VERSION
          echo "::set-output name=version::$VERSION"
      - name: Setup Java
        if: ${{ needs.prepare-release.outputs.release_created }}
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      - name: Setup Gradle
        if: ${{ needs.prepare-release.outputs.release_created }}
        uses: gradle/gradle-build-action@v2
      - name: Build jar
        if: ${{ needs.prepare-release.outputs.release_created }}
        run: ./gradlew build
      - name: Login in ACR
        if: ${{ needs.prepare-release.outputs.release_created }}
        uses: azure/docker-login@v1
        with:
          login-server: penworacr.azurecr.io
          username: ${{ secrets.PENWORACR_USERNAME }}
          password: ${{ secrets.PENWORACR_PASSWORD }}
      - name: Build and push image
        if: ${{ needs.prepare-release.outputs.release_created }}
        id: build-image
        env:
          REGISTRY: penworacr.azurecr.io
          REPOSITORY: alfred-api
          IMAGE_TAG: ${{ steps.read-version.outputs.version }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$REGISTRY/$REPOSITORY:$IMAGE_TAG"

  deploy-release:
    runs-on: ubuntu-latest
    needs:
      - generate-release
      - prepare-release
    steps:
      - name: Install kubectl
        if: ${{ needs.prepare-release.outputs.release_created }}
        uses: azure/setup-kubectl@v3
      - name: Set AKS context
        if: ${{ needs.prepare-release.outputs.release_created }}
        uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.PENWORAKS_KUBECONFIG }}
          context: PennyworthAKS
      - name: Deploy new image
        if: ${{ needs.prepare-release.outputs.release_created }}
        env:
          IMAGE: ${{ needs.generate-release.outputs.image }}
          CONTAINER: alfred-api
          DEPLOYMENT: alfred-api-deploy
        run: |
          kubectl set image deployment $DEPLOYMENT $CONTAINER=$IMAGE
