name: Deploy release

on:
  push:
    tags:
      - '*'

jobs:
  generate-release:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build-image.outputs.image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Read version
        id: read-version
        run: |
          VERSION=$(cat version.txt)
          echo Version read: $VERSION
          echo "::set-output name=version::$VERSION"
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build jar
        run: ./gradlew build
      - uses: azure/docker-login@v1
        with:
          login-server: penworacr.azurecr.io
          username: ${{ secrets.PENWORACR_USERNAME }}
          password: ${{ secrets.PENWORACR_PASSWORD }}
      - name: Build and push image
        id: build-image
        env:
          REGISTRY: penworacr.azurecr.io
          REPOSITORY: alfred-api
          IMAGE_TAG: ${{ steps.read-version.outputs.version }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$REGISTRY/$REPOSITORY:$IMAGE_TAG"

  deploy-release:
    runs-on: ubuntu-latest
    needs:
      - generate-release
    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
      - name: Set AKS context
        uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.PENWORAKS_KUBECONFIG }}
          context: PennyworthAKS
      - name: Deploy new image
        env:
          IMAGE: ${{ needs.generate-release.outputs.image }}
          CONTAINER: alfred-api
          DEPLOYMENT: alfred-api-deploy
        run: |
          kubectl set image deployment $DEPLOYMENT $CONTAINER=$IMAGE
