name: Prepare release

on:
  push:
    branches:
      - main

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Prepare release
        id: release-please
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          token: ${{secrets.GITHUB_TOKEN}}
      - name: Check outputs
        run: |
          echo release_created: ${{ steps.release-please.outputs.release_created }}
          echo tag_name: ${{ steps.release-please.outputs.tag_name }}
          echo major: ${{ steps.release-please.outputs.major }}
          echo minor: ${{ steps.release-please.outputs.minor }}
          echo patch: ${{ steps.release-please.outputs.patch }}
