name: Prepare release

on:
  push:
    branches:
      - main

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Prepare release
        id: release-please
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          token: ${{secrets.GITHUB_TOKEN}}
          release-type: simple
      - name: Check outputs
        env:
          RELEASE_CREATED: ${{ steps.release-please.outputs.release_created }}
          TAG_NAME: ${{ steps.release-please.outputs.tag_name }}
          MAJOR: ${{ steps.release-please.outputs.major }}
          MINOR: ${{ steps.release-please.outputs.minor }}
          PATCH: ${{ steps.release-please.outputs.patch }}
        run: |
          echo release_created: $RELEASE_CREATED
          echo tag_name: $TAG_NAME
          echo major: $MAJOR
          echo minor: $MINOR
          echo patch: $PATCH
